# Generated by Django 5.0.2 on 2024-03-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageURL', models.ImageField(upload_to='evlonPosts/')),
                ('caption', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('timeRemaining', models.IntegerField()),
                ('Attendance', models.IntegerField()),
                ('likesCount', models.IntegerField()),
                ('commentsCount', models.IntegerField()),
                ('smallProfile', models.ImageField(upload_to='evlonPosts/')),
                ('name', models.CharField(max_length=50)),
                ('counter', models.IntegerField()),
            ],
            options={
                'db_table': 'EvlonPosts',
            },
        ),
    ]
