# Generated by Django 5.0.2 on 2024-04-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evlon', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imageURL',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='smallProfile',
            field=models.CharField(default='./Rong.jpg', max_length=200),
        ),
    ]
